Translated in Korean
Dimillian/ACHNBrowserUI pull request #316
Opened 2020-08-18 13:48 UTC by AndyH0ng

2020-09-02 16:23 UTC, ericlewis approved these changes
this is partial at best but sure.

2020-09-03 01:02 UTC, AndyH0ng commented
Oh so am i supposed to merge with legacy?

2020-09-03 05:12 UTC, TheVaan commented
We won't release an other legacy update. Next up is iOS 14 with our iOS 14 app release.

2020-09-24 05:01 UTC, ericlewis commented
@AndyH0ng this is incomplete so we can't merge at all- please update!

2020-09-24 05:03 UTC, ericlewis requested changes
please do all

2020-09-24 05:18 UTC, TheVaan commented
You can find all translations in the German and French file.
The English file only contains translations where the key is different to the text we want to show. In the other files you will find more keys to translate. You don't have to understand the translated part of each line because the "real English string" is the key.

2020-09-24 07:45 UTC, AndyH0ng commented
Oh i get it now. Thanks 👍

2020-10-05 06:08 UTC, TheVaan commented
Really good work! Great! Just a few strings that are still in French in your file and your are 100 percent done! Thank you!

2025-09-22 00:06 UTC, closed without merging